version: 2.1

# Define the jobs and workflows for CircleCI
jobs:
  # Job to install dependencies and run the tests
  test:
    docker:
      - image: cimg/python:3.9  # Use a CircleCI Python Docker image (version 3.9)
    steps:
      # Step 1: Checkout the code from the repository
      - checkout

      # Step 2: Install dependencies (using pip and requirements.txt)
      - run:
          name: Install dependencies
          command: |
            python -m venv venv  # Create a virtual environment
            . venv/bin/activate  # Activate the virtual environment
            pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 3: Run the tests using pytest
      - run:
          name: Run tests
          command: |
            . venv/bin/activate  # Activate the virtual environment
            pytest tests  # Run tests located in the 'tests' directory

# Define workflows to orchestrate jobs
workflows:
  version: 2
  test-workflow:
    jobs:
      - test  # Run the test job in the workflow
